const medias = {
    lista_productos: [
      {
        marca: "TM",
        modelo: "scirocco",
        anio: 2023,
        color: "negro",
        comentarios: "",
      },
      {
        marca: "TM",
        modelo: "scirocco",
        anio: 2023,
        color: "negro",
        comentarios: "",
      },
      {
        marca: "TM",
        modelo: "scirocco",
        anio: 2023,
        color: "negro",
        comentarios: "",
      },
      {
        marca: "TM",
        modelo: "scirocco",
        anio: 2023,
        color: "negro",
        comentarios: "",
      },
      {
        marca: "TM",
        modelo: "scirocco",
        anio: 2023,
        color: "negro",
        comentarios: "",
      },
      {
        marca: "TM",
        modelo: "scirocco",
        anio: 2023,
        color: "negro",
        comentarios: "",
      },
      {
        marca: "TM",
        modelo: "scirocco",
        anio: 2023,
        color: "negro",
        comentarios: "",
      },
      {
        marca: "TM",
        modelo: "scirocco",
        anio: 2023,
        color: "negro",
        comentarios: "",
      },
      {
        marca: "TM",
        modelo: "scirocco",
        anio: 2023,
        color: "negro",
        comentarios: "",
      },
      {
        marca: "TM",
        modelo: "scirocco",
        anio: 2023,
        color: "negro",
        comentarios: "",
      },
      {
        marca: "TM",
        modelo: "scirocco",
        anio: 2023,
        color: "negro",
        comentarios: "",
      },
      {
        marca: "TM",
        modelo: "scirocco",
        anio: 2023,
        color: "negro",
        comentarios: "",
      },
      {
        marca: "TM",
        modelo: "scirocco",
        anio: 2023,
        color: "negro",
        comentarios: "",
      },
      {
        marca: "TM",
        modelo: "scirocco",
        anio: 2023,
        color: "negro",
        comentarios: "",
      },
      {
        marca: "TM",
        modelo: "scirocco",
        anio: 2023,
        color: "negro",
        comentarios: "",
      },
      {
        marca: "TM",
        modelo: "scirocco",
        anio: 2023,
        color: "negro",
        comentarios: "",
      },
      {
        marca: "TM",
        modelo: "scirocco",
        anio: 2023,
        color: "negro",
        comentarios: "",
      },
      {
        marca: "TM",
        modelo: "scirocco",
        anio: 2023,
        color: "negro",
        comentarios: "",
      },
      {
        marca: "TM",
        modelo: "scirocco",
        anio: 2023,
        color: "negro",
        comentarios: "",
      },
      {
        marca: "TM",
        modelo: "scirocco",
        anio: 2023,
        color: "negro",
        comentarios: "",
      },
      {
        marca: "TM",
        modelo: "scirocco",
        anio: 2023,
        color: "negro",
        comentarios: "",
      },
      {
        marca: "TM",
        modelo: "scirocco",
        anio: 2023,
        color: "negro",
        comentarios: "",
      },
      {
        marca: "TM",
        modelo: "scirocco",
        anio: 2023,
        color: "negro",
        comentarios: "",
      },
      {
        marca: "TM",
        modelo: "scirocco",
        anio: 2023,
        color: "negro",
        comentarios: "",
      },
      {
        marca: "TM",
        modelo: "scirocco",
        anio: 2023,
        color: "negro",
        comentarios: "",
      },
      {
        marca: "TM",
        modelo: "scirocco",
        anio: 2023,
        color: "negro",
        comentarios: "",
      },
      {
        marca: "TM",
        modelo: "scirocco",
        anio: 2023,
        color: "negro",
        comentarios: "",
      },
      {
        marca: "TM",
        modelo: "scirocco",
        anio: 2023,
        color: "negro",
        comentarios: "",
      },
      {
        marca: "TM",
        modelo: "scirocco",
        anio: 2023,
        color: "negro",
        comentarios: "",
      },
      {
        marca: "TM",
        modelo: "scirocco",
        anio: 2023,
        color: "negro",
        comentarios: "",
      },
      {
        marca: "TM",
        modelo: "scirocco",
        anio: 2023,
        color: "negro",
        comentarios: "",
      },
      {
        marca: "TM",
        modelo: "scirocco",
        anio: 2023,
        color: "negro",
        comentarios: "",
      },
      {
        marca: "TM",
        modelo: "scirocco",
        anio: 2023,
        color: "negro",
        comentarios: "",
      },
      {
        marca: "TM",
        modelo: "scirocco",
        anio: 2023,
        color: "negro",
        comentarios: "",
      }
    ]
  };
  
  module.exports = medias;