const medias = {
  
    lista_usuarios:[ {
        email: 'usuario@gmail.com',
        usuario: 'nombredeusuario',
        contraseña: 'contraseña123',
        fechaNacimiento: '1990-01-01', 
        nroDocumento: 123456789,
        fotoPerfil: 'ruta/a/la/foto.jpg',
    },
    {
      email: 'usuario@gmail.com',
      usuario: 'nombredeusuario',
      contraseña: 'contraseña123',
      fechaNacimiento: '1990-01-01', 
      nroDocumento: 123456789,
      fotoPerfil: 'ruta/a/la/foto.jpg',
  },
  {
    email: 'usuario@gmail.com',
    usuario: 'nombredeusuario',
    contraseña: 'contraseña123',
    fechaNacimiento: '1990-01-01', 
    nroDocumento: 123456789,
    fotoPerfil: 'ruta/a/la/foto.jpg',
},
{
  email: 'usuario@gmail.com',
  usuario: 'nombredeusuario',
  contraseña: 'contraseña123',
  fechaNacimiento: '1990-01-01', 
  nroDocumento: 123456789,
  fotoPerfil: 'ruta/a/la/foto.jpg',
},
{
  email: 'usuario@gmail.com',
  usuario: 'nombredeusuario',
  contraseña: 'contraseña123',
  fechaNacimiento: '1990-01-01', 
  nroDocumento: 123456789,
  fotoPerfil: 'ruta/a/la/foto.jpg',
},
{
  email: 'usuario@gmail.com',
  usuario: 'nombredeusuario',
  contraseña: 'contraseña123',
  fechaNacimiento: '1990-01-01', 
  nroDocumento: 123456789,
  fotoPerfil: 'ruta/a/la/foto.jpg',
},
{
  email: 'usuario@gmail.com',
  usuario: 'nombredeusuario',
  contraseña: 'contraseña123',
  fechaNacimiento: '1990-01-01', 
  nroDocumento: 123456789,
  fotoPerfil: 'ruta/a/la/foto.jpg',
},
{
  email: 'usuario@gmail.com',
  usuario: 'nombredeusuario',
  contraseña: 'contraseña123',
  fechaNacimiento: '1990-01-01', 
  nroDocumento: 123456789,
  fotoPerfil: 'ruta/a/la/foto.jpg',
},
{
  email: 'usuario@gmail.com',
  usuario: 'nombredeusuario',
  contraseña: 'contraseña123',
  fechaNacimiento: '1990-01-01', 
  nroDocumento: 123456789,
  fotoPerfil: 'ruta/a/la/foto.jpg',
},
{
  email: 'usuario@gmail.com',
  usuario: 'nombredeusuario',
  contraseña: 'contraseña123',
  fechaNacimiento: '1990-01-01', 
  nroDocumento: 123456789,
  fotoPerfil: 'ruta/a/la/foto.jpg',
},
  
  ],
 lista_productos: [
      {
        marca: "TM",
        modelo: "scirocco",
        anio: 2023,
        color: "negro",
        comentarios: "",
      },
      {
        marca: "TM",
        modelo: "scirocco",
        anio: 2023,
        color: "negro",
        comentarios: "",
      },
      {
        marca: "TM",
        modelo: "scirocco",
        anio: 2023,
        color: "negro",
        comentarios: "",
      },
      {
        marca: "TM",
        modelo: "scirocco",
        anio: 2023,
        color: "negro",
        comentarios: "",
      },
      {
        marca: "TM",
        modelo: "scirocco",
        anio: 2023,
        color: "negro",
        comentarios: "",
      },
      {
        marca: "TM",
        modelo: "scirocco",
        anio: 2023,
        color: "negro",
        comentarios: "",
      },
      {
        marca: "TM",
        modelo: "scirocco",
        anio: 2023,
        color: "negro",
        comentarios: "",
      },
      {
        marca: "TM",
        modelo: "scirocco",
        anio: 2023,
        color: "negro",
        comentarios: "",
      },
      {
        marca: "TM",
        modelo: "scirocco",
        anio: 2023,
        color: "negro",
        comentarios: "",
      },
      {
        marca: "TM",
        modelo: "scirocco",
        anio: 2023,
        color: "negro",
        comentarios: "",
      },
      {
        marca: "TM",
        modelo: "scirocco",
        anio: 2023,
        color: "negro",
        comentarios: "",
      },
      {
        marca: "TM",
        modelo: "scirocco",
        anio: 2023,
        color: "negro",
        comentarios: "",
      },
      {
        marca: "TM",
        modelo: "scirocco",
        anio: 2023,
        color: "negro",
        comentarios: "",
      },
      {
        marca: "TM",
        modelo: "scirocco",
        anio: 2023,
        color: "negro",
        comentarios: "",
      },
      {
        marca: "TM",
        modelo: "scirocco",
        anio: 2023,
        color: "negro",
        comentarios: "",
      },
      {
        marca: "TM",
        modelo: "scirocco",
        anio: 2023,
        color: "negro",
        comentarios: "",
      },
      {
        marca: "TM",
        modelo: "scirocco",
        anio: 2023,
        color: "negro",
        comentarios: "",
      },
      {
        marca: "TM",
        modelo: "scirocco",
        anio: 2023,
        color: "negro",
        comentarios: "",
      },
      {
        marca: "TM",
        modelo: "scirocco",
        anio: 2023,
        color: "negro",
        comentarios: "",
      },
      {
        marca: "TM",
        modelo: "scirocco",
        anio: 2023,
        color: "negro",
        comentarios: "",
      },
      {
        marca: "TM",
        modelo: "scirocco",
        anio: 2023,
        color: "negro",
        comentarios: "",
      },
      {
        marca: "TM",
        modelo: "scirocco",
        anio: 2023,
        color: "negro",
        comentarios: "",
      },
      {
        marca: "TM",
        modelo: "scirocco",
        anio: 2023,
        color: "negro",
        comentarios: "",
      },
      {
        marca: "TM",
        modelo: "scirocco",
        anio: 2023,
        color: "negro",
        comentarios: "",
      },
      {
        marca: "TM",
        modelo: "scirocco",
        anio: 2023,
        color: "negro",
        comentarios: "",
      },
      {
        marca: "TM",
        modelo: "scirocco",
        anio: 2023,
        color: "negro",
        comentarios: "",
      },
      {
        marca: "TM",
        modelo: "scirocco",
        anio: 2023,
        color: "negro",
        comentarios: "",
      },
      {
        marca: "TM",
        modelo: "scirocco",
        anio: 2023,
        color: "negro",
        comentarios: "",
      },
      {
        marca: "TM",
        modelo: "scirocco",
        anio: 2023,
        color: "negro",
        comentarios: "",
      },
      {
        marca: "TM",
        modelo: "scirocco",
        anio: 2023,
        color: "negro",
        comentarios: "",
      },
      {
        marca: "TM",
        modelo: "scirocco",
        anio: 2023,
        color: "negro",
        comentarios: "",
      },
      {
        marca: "TM",
        modelo: "scirocco",
        anio: 2023,
        color: "negro",
        comentarios: "",
      },
      {
        marca: "TM",
        modelo: "scirocco",
        anio: 2023,
        color: "negro",
        comentarios: "",
      },
      {
        marca: "TM",
        modelo: "scirocco",
        anio: 2023,
        color: "negro",
        comentarios: "",
      }
    ]
  };
  
  
 

  module.exports = medias;